version: "3.7"

services:
  server:
    image: server:v1
    ports:
      - "8080:8080"
    restart: unless-stopped
  client:
    image: client:v1
    ports:
      - "3000:3000"
    restart: unless-stopped